{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .project }}
  source:
    repoURL: {{ .source.repoURL }}
    targetRevision: {{ .source.targetRevision }}
    path: {{ .source.path }}
    {{- if .source.helm }}
    helm:
      {{- toYaml .source.helm | nindent 6 }}
    {{- end }}
  destination:
    server: {{ .destination.server }}
    namespace: {{ .destination.namespace }}
  {{- if .syncPolicy }}
  syncPolicy:
    {{- if .syncPolicy.automated }}
    automated:
      {{- toYaml .syncPolicy.automated | nindent 6 }}
    {{- end }}
    {{- if .syncPolicy.syncOptions }}
    syncOptions:
      {{- toYaml .syncPolicy.syncOptions | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
